apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaibai-user-deployment
spec:
  selector:
    matchLabels:
      app: kaibai-user
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: kaibai-user
    spec:
      imagePullSecrets:
        - name: aliregistry
      containers:
        - name: kaibai-user-deploy
          image: registry.cn-hangzhou.aliyuncs.com/wyswill_docker/kai_bai_user_service:0d0c4dfd
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kaibai-user-svc
  labels:
    app: kaibai-user
spec:
  type: NodePort
  selector:
    app: kaibai-user
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
