apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kaibaiservice
spec:
  components:
    - name: kaibaiservice
      type: webservice
      properties:
        image: registry.cn-hangzhou.aliyuncs.com/wyswill_docker/kai_bai_service:0.0.1
        ports:
          - port: 3000
            expose: true
            protocol: "TCP"
        cpu: "0.5"
        memory: 512Mi
      traits:
        - type: scaler
          properties:
            replicas: 2
        - type: gateway
          properties:
            domain: kaibaiservice.local.com
            gatewayHost: 127.0.0.1
            http:
              "/": 3000
