apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaibai-user-deployment
spec:
  selector:
    matchLabels:
      app: kaibai-user
  replicas: 1
  template:
    metadata:
      labels:
        app: kaibai-user
    spec:
      imagePullSecrets:
        - name: aliregistry
      containers:
        - name: nginx
          image: registry.cn-hangzhou.aliyuncs.com/wyswill_docker/kai_bai_user_service:a93b5d3a
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: kaibai-user-svc
  labels:
    app: kaibai-user
spec:
  type: NodePort
  selector:
    app: kaibai-user
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3000
