apiVersion: v1
kind: Pod
metadata:
  name: kaibaibizservice
  labels:
    name: kaibaibizservice
spec:
  restartPolicy: Always
  containers:
    - name: kaibaibizservice
      image: registry.cn-hangzhou.aliyuncs.com/wyswill_docker/kai_bai_service:d39a818d
      resources:
        requests:
          memory: '128Mi'
          cpu: '500m'
        limits:
          memory: '500Mi'
          cpu: '1000m'

      ports:
        - name: http
          containerPort: 3000
          protocol: TCP
