name: CI
on:
  push:
    branches:
      - dev
  # pull_request:
  #   branches: ['master']
  #   types: [closed]
jobs:
  build:
    runs-on: docker-latest
    steps:
      - name: pull repo
        shell: bash
        run: |
          echo "git clone http://192.168.2.128:3000/wyswill/kai_bai/kaibai_user_service"
          git clone -b release http://192.168.2.128:3000/wyswill/kai_bai/kaibai_user_service .
          ls -al
      - name: build_img
        run: sh build.sh build_img
      - name: login_ali
        run: sh build.sh login_ali
      - name: push_img
        run: sh build.sh push_img
