name: CI
on:
  pull_request:
    branches: ['master']
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        shell: bash
        run: |
          echo "git clone "
          git clone  https://github.com/Hemp-bandit/kaibai_biz_service .
          ls -al
      - name: build_img
        run: bash build.sh build_img
      - name: login_ali
        shell: bash
        run: |
          docker login --username=15717827650 -p ${{secrets.ALI_IMG_HUB_PASS}} registry.cn-hangzhou.aliyuncs.com
      - name: push_img
        run: bash build.sh push_img
